swagger: '2.0'
info:
  version: '1.0.0'
  title: Swagger Hand range trainer API
  description: Hand range trainer API by swagger-2.0 specification
  termsOfService: https://ocw.mit.edu/terms/
  contact:
    name: Soloviev Dmitry
    email: dgsoloviev@gmail.com
    url: https://github.com/soulaway
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost:8080
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /range/:
    get:
      description: Returns all ranges from the system
      operationId: findRanges
      produces:
        - application/json
      responses:
        '200':
          description: ranges response
          schema:
            type: array
            items:
              $ref: '#/definitions/Range'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    put:
      description: Updats existed range.
      operationId: updateRange
      produces:
        - application/json
      parameters:
        - name: range
          in: body
          description: Range to update
          required: true
          schema:
            $ref: '#/definitions/Range'
      responses:
        '200':
          description: ranges response
          schema:
            $ref: '#/definitions/Range'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /range/new/{rangeName}:
    post:
      description: Creates a new range in the store.  Duplicates are disallowed
      operationId: addRange
      produces:
        - application/json
      parameters:
        - name: rangeName
          in: path
          description: Range added
          required: true
          type: string
      responses:
        '200':
          description: ranges response
          schema:
            $ref: '#/definitions/Range'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /range/{rangeId}:
    get:
      description: Returns a Range based on a single ID
      operationId: findRangeById
      produces:
        - application/json
      parameters:
        - name: rangeId
          in: path
          description: ID of range to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: range response
          schema:
            $ref: '#/definitions/Range'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    delete:
      description: deletes a single Range based on the ID
      operationId: deleteRange
      parameters:
        - name: rangeId
          in: path
          description: ID of the range to delete
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: range deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  Range:
    type: object
    required:
      - rangeId
      - rangeName
    properties:
      rangeId:
        type: integer
        format: int64
      rangeName:
        type: string
      tag:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
