swagger: '2.0'
info:
  version: '1.0.0'
  title: Swagger Hand range trainer API
  description: Hand range trainer API by swagger-2.0 specification
  termsOfService: https://ocw.mit.edu/terms/
  contact:
    name: Soloviev Dmitry
    email: dgsoloviev@gmail.com
    url: https://github.com/soulaway
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /range:
    get:
      description: Returns all ranges from the system
      operationId: findRanges
      produces:
        - application/json
      responses:
        '200':
          description: ranges response
          schema:
            type: array
            items:
              $ref: '#/definitions/Ranges'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      description: Creates a new range in the store.  Duplicates are disallowed
      operationId: addRange
      produces:
        - application/json
      parameters:
        - name: range
          in: body
          description: Pet to add to the store
          required: true
          schema:
            $ref: '#/definitions/Range'
      responses:
        '200':
          description: ranges response
          schema:
            $ref: '#/definitions/Range'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /range/{id}:
    get:
      description: Returns a Range based on a single ID
      operationId: findRangeById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of range to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: range response
          schema:
            $ref: '#/definitions/Range'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    delete:
      description: deletes a single Range based on the ID
      operationId: deleteRange
      parameters:
        - name: id
          in: path
          description: ID of the range to delete
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: range deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  Range:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  Ranges:
    type: object
    description: Common collection holder for xml binding of Group model
    properties:
      group:
        type: array
        description: Group list
        items:
          $ref: '#/definitions/Range'
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
