/**
 * Swagger Hand range trainer API
 * Hand range trainer API by swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dgsoloviev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ErrorModel {
    code: number;

    message: string;

}
