/**
 * Swagger Hand range trainer API
 * Hand range trainer API by swagger-2.0 specification
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dgsoloviev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Common collection holder for xml binding of Group model
 */
export interface Ranges {
    /**
     * Group list
     */
    group?: Array<models.Range>;

}
